exclude: ^static/.*|assets/.*|/migrations/.*|\.min\.js$|\.min\.css$|\.css\.map$|\.min\.js$|\.js\.map$|\.svg$
default_stages: [commit]
default_language_version:
   python: python3.11

repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.4.4
    hooks:
      - id: ruff

  - repo: local
    hooks:
      - id: frontend-checks
        name: Frontend Checks
        entry: cmd.exe /c "cd frontend && npm run lint"
        language: system
        files: ^frontend/.*\.(js|jsx|ts|tsx)$
        pass_filenames: false
