# \micro_ai\docker-compose.yml

services:
  db:
    container_name: db
    image: postgres
    # persist data beyond lifetime of container
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=micro_ai
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    networks:
      - microaiNetwork
    healthcheck:
      test: pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}
      interval: 2s
      retries: 10
  redis:
    container_name: redis
    image: redis
    # persistent storage
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    networks:
      - microaiNetwork
    healthcheck:
      test: bash -c 'exec 6<>/dev/tcp/redis/6379'
      interval: 2s
      retries: 10
  web:
    container_name: web
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/code
      - media_data:/code/media
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    restart: unless-stopped
    networks:
      - microaiNetwork
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
  celery:
    container_name: celery
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    command: celery -A micro_ai worker -l INFO --beat --concurrency 2
    volumes:
      - ./backend:/code
      - media_data:/code/media
    env_file:
      - ./.env
    networks:
      - microaiNetwork
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    expose:
      - "3000"
    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules
    networks:
      - microaiNetwork
    env_file:
      - ./.env
    environment:
      - NODE_ENV=development
      - WATCHPACK_POLLING=true
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.local.conf:/etc/nginx/conf.d/default.conf
    networks:
      - microaiNetwork
    depends_on:
      - frontend

volumes:
  postgres_data:
  redis_data:
  static:
  media_data:

networks:
  microaiNetwork:
    driver: bridge