# Multi-stage Docker buildfile
# See https://docs.docker.com/build/guide/multi-stage/

# Stage 1: Build the python dependencies
FROM python:3.11-slim-bookworm as build-python
RUN apt-get update \
  && apt-get install -y build-essential libpq-dev
COPY ./requirements /requirements
RUN pip wheel --no-cache-dir --no-deps --wheel-dir /wheels \
    -r /requirements/requirements.txt \
    -r /requirements/prod-requirements.txt

# Stage 2: Build the front end files
FROM node:20-bookworm-slim AS build-node
RUN node -v && npm -v
WORKDIR /code
COPY *.json *.js .babelrc /code/
COPY assets /code/assets/
COPY api-client /code/api-client/

RUN npm install

# Build needs everything because it needs to be able to do the tailwind class detection/purging stuff
COPY . /code
RUN npm run build

# Stage 3: Build the final image
FROM python:3.11-slim-bookworm
ENV PYTHONUNBUFFERED 1
ENV DEBUG 0

RUN apt-get update \
  && apt-get install -y \
  curl \
  libpq-dev \
  gettext \
  && apt-get purge -y --auto-remove -o APT::AutoRemove::RecommendsImportant=false \
  && rm -rf /var/lib/apt/lists/*

RUN addgroup --system django \
    && adduser --system --ingroup django django \
    && mkdir -p /code/media \
    && chown -R django:django /code/media

# Copy Python dependencies from the previous stage
COPY --from=build-python /wheels /wheels
COPY ./requirements /requirements
RUN pip install --no-index --find-links=/wheels \
    -r /requirements/requirements.txt \
    -r /requirements/prod-requirements.txt \
    && rm -rf /wheels \
    && rm -rf /root/.cache/pip/*

WORKDIR /code

# Copy the application code
COPY --chown=django:django . /code
COPY --from=build-node /code/static /code/static

RUN mkdir static_root && chown django:django -R static_root

USER django

# Copy the startup script
COPY --chown=django:django deploy/docker_startup.sh /start
RUN chmod +x /start

# Use the entrypoint script to start the application
CMD ["/start"]
