# \micro_ai\Dockerfile.dev

FROM python:3.11-bookworm
ENV PYTHONUNBUFFERED=1

# install node/npm (Bookworm-safe, ARM-safe)
RUN apt-get update -y \
    && apt-get install -y curl ca-certificates gnupg \
    && curl -fsSL https://deb.nodesource.com/setup_20.x | bash - \
    && apt-get install -y nodejs

# install Tesseract OCR and other dependencies
RUN apt-get update \
  && apt-get install -y \
  curl \
  libpq-dev \
  gettext \
  tesseract-ocr \
  && apt-get purge -y --auto-remove -o APT::AutoRemove::RecommendsImportant=false \
  && rm -rf /var/lib/apt/lists/*

# create code directory
RUN mkdir /code
WORKDIR /code

# install python requirements
RUN pip install --upgrade pip wheel pip-tools setuptools build

# copy just requirements and install before rest of code to avoid having to
# reinstall packages during build every time code changes
COPY requirements /requirements/
RUN pip-compile /requirements/requirements.in \
    && pip-compile /requirements/dev-requirements.in \
    && pip install --no-build-isolation -r /requirements/requirements.txt \
    && pip install --no-build-isolation -r /requirements/dev-requirements.txt

# copy code files
COPY . /code/
