# Generated by Django 5.1.6 on 2025-03-19 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserAPIKey',
        ),
    ]
