# Generated by Django 5.0.6 on 2025-01-26 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_avatar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': [('is_beta_tester', 'Can access beta features')], 'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
