# Generated by Django 5.0.6 on 2025-01-16 06:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('microapps', '0041_remove_run_prompt_run_app_hash_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('credits_allocated', models.FloatField()),
                ('credits_used', models.FloatField()),
                ('credits_remaining', models.FloatField()),
                ('status', models.CharField(choices=[('open', 'open'), ('closed', 'closed')], default='open', max_length=8)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UsageEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credits_charged', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('billing_cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscriptions.billingcycle')),
                ('run_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='microapps.run')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
