# Generated by Django 5.0.6 on 2025-01-17 09:46

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_subscriptiondetails'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SubscriptionDetails',
            new_name='SubscriptionDetail',
        ),
    ]
