# Generated by Django 5.0.6 on 2025-01-22 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0004_subscriptionconfiguration'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubscriptionDetail',
        ),
    ]
