# Generated by Django 5.1.6 on 2025-02-18 13:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0006_alter_billingcycle_options_billingcycle_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StripeCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(help_text='ID of the Stripe customer', max_length=255, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stripe_customers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_id', models.CharField(help_text='ID of the Stripe subscription', max_length=255, unique=True)),
                ('price_id', models.CharField(blank=True, help_text='ID of the price associated with the subscription', max_length=255, null=True)),
                ('status', models.CharField(blank=True, choices=[('active', 'Active'), ('canceled', 'Canceled'), ('incomplete', 'Incomplete'), ('incomplete_expired', 'Incomplete Expired'), ('past_due', 'Past Due'), ('trialing', 'Trialing'), ('unpaid', 'Unpaid')], max_length=20, null=True)),
                ('period_start', models.BigIntegerField(blank=True, help_text='Unix timestamp for the start of the period', null=True)),
                ('period_end', models.BigIntegerField(blank=True, help_text='Unix timestamp for the end of the period', null=True)),
                ('cancel_at_period_end', models.BooleanField(default=False)),
                ('canceled_at', models.BigIntegerField(blank=True, help_text='Unix timestamp when the subscription was canceled', null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='subscriptions.stripecustomer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='billingcycle',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='subscriptions.subscription'),
        ),
        migrations.AlterField(
            model_name='subscriptionconfiguration',
            name='subscription',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='configuration', to='subscriptions.subscription'),
        ),
    ]
