# Generated by Django 5.1.6 on 2025-03-23 02:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0009_stripecustomer_created_at_stripecustomer_updated_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='usageevent',
            name='consumer',
            field=models.ForeignKey(
                blank=True, 
                null=True, 
                on_delete=django.db.models.deletion.SET_NULL, 
                related_name='consumed_usage_events', 
                to=settings.AUTH_USER_MODEL,
                db_index=True
            ),
        ),
    ]
