# Generated by Django 5.1.6 on 2025-03-23 10:42
# Adds a source field to the Subscription model to distinguish between Stripe and Internal subscriptions
# Sets Stripe customer and Stripe subscription ID to optional since internal subscriptions don't have them

import django.db.models.deletion
from django.db import migrations, models


def update_stripe_sources(apps, schema_editor):
    Subscription = apps.get_model('subscriptions', 'Subscription')
    Subscription.objects.filter(subscription_id__isnull=False).update(source='stripe')


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0010_usageevent_consumer'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='source',
            field=models.CharField(choices=[('stripe', 'Stripe'), ('internal', 'Internal')], default='internal', max_length=20),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='subscriptions.stripecustomer'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='subscription_id',
            field=models.CharField(blank=True, help_text='ID of the Stripe subscription (only required for Stripe subscriptions)', max_length=255, null=True, unique=True),
        ),
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.CheckConstraint(
                check=models.Q(
                    source='internal'
                ) | models.Q(
                    source='stripe',
                    subscription_id__isnull=False
                ),
                name='stripe_subscriptions_require_id'
            )
        ),
        migrations.RunPython(update_stripe_sources, reverse_code=migrations.RunPython.noop),
    ]
