# Generated by Django 5.1.6 on 2025-03-24 01:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0011_subscription_source_alter_subscription_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usageevent',
            name='top_up',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='subscriptions.topuptosubscription'),
        ),
    ]
