# Generated by Django 5.1.6 on 2025-03-27 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0012_add_top_up_reference_to_usage_event'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='subscription',
            name='stripe_subscriptions_require_id',
        ),
    ]
