# Generated by Django 5.1.6 on 2025-03-30 17:59
# No-op: team field removal was handled outside migration state; dynamic ops broke migrate.

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0013_remove_subscription_stripe_subscriptions_require_id'),
    ]

    operations = []
