# Generated by Django 5.1.6 on 2025-03-30 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0013_remove_subscription_stripe_subscriptions_require_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billingcycle',
            name='team',
        ),
    ]