# Generated by Django 5.1.6 on 2025-07-18 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0015_coupon_couponusage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='action',
            field=models.CharField(choices=[('increase_max_apps', 'Increase Max Apps'), ('increase_max_apps_and_credits', 'Increase Max Apps and Credits')], max_length=50),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='additional_data',
            field=models.JSONField(default=dict, help_text="JSON data for the action (e.g., {'max_apps': 10, 'credits': 100000})"),
        ),
    ]
