# Generated by Django 5.2.5 on 2026-06-04 14:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microapps', '0068_score_analysis_snapshot'),
        ('subscriptions', '0016_alter_coupon_action_alter_coupon_additional_data'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(help_text='Positive for grants, negative for spends.')),
                ('reason', models.CharField(choices=[('monthly_grant', 'Monthly grant'), ('usage', 'Usage'), ('topup', 'Top-up'), ('coupon', 'Coupon'), ('adjustment', 'Manual adjustment')], max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('consumer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consumed_credit_transactions', to=settings.AUTH_USER_MODEL)),
                ('run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='microapps.run')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CreditWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_credits', models.IntegerField(default=0, help_text='Tier credits for the current period. Reset to the tier allotment each period.')),
                ('topup_credits', models.IntegerField(default=0, help_text='Purchased one-off credits. Never reset; roll over across periods.')),
                ('reset_at', models.DateTimeField(help_text='When subscription_credits should next be refilled to the tier allotment.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
