# Development configuration for microai-frontend

services:
  nginx:
    container_name: nginx
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
      - ./fallback:/usr/share/nginx/html  # Mount fallback page directory

    networks:
      micronet:
        ipv4_address: 172.25.0.4
    restart: unless-stopped

networks:
  micronet:
    external: true