# Generated by Django 5.1.6 on 2025-04-24 05:46

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LTIConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issuer', models.CharField(max_length=255, unique=True)),
                ('client_id', models.CharField(max_length=100)),
                ('auth_login_url', models.URLField()),
                ('auth_token_url', models.URLField()),
                ('key_set_url', models.URLField()),
                ('deployment_ids', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), default=list, size=None)),
                ('redirect_url', models.URLField()),
            ],
        ),
    ]
