# Generated by Django 5.0.6 on 2024-07-08 12:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('global_microapps', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.TextField()),
                ('label', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='KnowledgeBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Microapps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('explanation', models.TextField()),
                ('shared_assets', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=10)),
                ('knowledge_base', models.CharField(max_length=50)),
                ('max_output', models.IntegerField()),
                ('temperature', models.FloatField()),
                ('top_p', models.FloatField()),
                ('frequency_penalty', models.FloatField()),
                ('presence_penalty', models.FloatField()),
                ('max_prompts', models.IntegerField()),
                ('copy_allowed', models.BooleanField()),
                ('app_json', models.JSONField()),
                ('global_ma_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='global_microapps.globalmicroapps')),
            ],
        ),
        migrations.CreateModel(
            name='AssetsMaJoin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='microapps.assets')),
                ('ma_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='microapps.microapps')),
            ],
        ),
        migrations.CreateModel(
            name='MicroAppUserJoin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('view', 'View'), ('admin', 'Admin')], max_length=10)),
                ('ma_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='microapps.microapps')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Run',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('assistant_id', models.TextField()),
                ('thread_id', models.TextField()),
                ('satisfaction', models.IntegerField()),
                ('prompt', models.TextField()),
                ('response', models.TextField()),
                ('credits', models.FloatField()),
                ('cost', models.FloatField()),
                ('ma_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='microapps.microapps')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
