# Generated by Django 5.0.6 on 2024-07-11 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microapps', '0004_alter_run_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='run',
            name='cost',
            field=models.DecimalField(decimal_places=10, max_digits=20),
        ),
    ]
