# Generated by Django 5.0.6 on 2024-07-15 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0001_initial'),
        ('microapps', '0007_alter_run_cost'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Microapps',
            new_name='Microapp',
        ),
    ]
