# Generated by Django 5.0.6 on 2024-07-22 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microapps', '0009_rename_assets_asset'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='ai_model',
            field=models.CharField(default='gpt-3.5-turbo', max_length=20),
        ),
        migrations.AddField(
            model_name='run',
            name='frequency_penalty',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='run',
            name='input_tokens',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='run',
            name='max_tokens',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='run',
            name='minimum_score',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='run',
            name='no_submission',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='run',
            name='output_tokens',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='run',
            name='presence_penalty',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='run',
            name='price_input_token_1M',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='run',
            name='price_output_token_1M',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='run',
            name='rubric',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='run',
            name='run_passed',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='run',
            name='run_score',
            field=models.CharField(default='1', max_length=10),
        ),
        migrations.AddField(
            model_name='run',
            name='scored_run',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='run',
            name='temperature',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='run',
            name='top_p',
            field=models.FloatField(default=0),
        ),
    ]
