# Generated by Django 5.0.6 on 2024-07-22 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microapps', '0010_run_ai_model_run_frequency_penalty_run_input_tokens_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='run',
            name='input_tokens',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='run',
            name='max_tokens',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='run',
            name='output_tokens',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='run',
            name='rubric',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='run',
            name='run_score',
            field=models.CharField(max_length=10),
        ),
    ]
