# Generated by Django 5.0.6 on 2024-07-24 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microapps', '0012_alter_run_ai_model_alter_run_frequency_penalty_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='run',
            name='run_score',
            field=models.JSONField(),
        ),
    ]
