# Generated by Django 5.0.6 on 2024-07-25 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microapps', '0014_run_skippable_phase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='run',
            name='response',
            field=models.TextField(blank=True),
        ),
    ]
