# Generated by Django 5.0.6 on 2024-08-02 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('microapps', '0015_alter_run_response'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='microapp',
            name='global_ma_id',
        ),
    ]
