# Generated by Django 5.0.6 on 2024-08-02 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('microapps', '0016_alter_microappuserjoin_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='microapp',
            name='global_ma_id',
        ),
    ]
