# Generated by Django 5.0.6 on 2024-08-05 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microapps', '0016_remove_microapp_global_ma_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='microappuserjoin',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('owner', 'Owner')], max_length=10),
        ),
    ]
