# Generated by Django 5.0.6 on 2024-08-07 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microapps', '0017_alter_microappuserjoin_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='run',
            name='ai_model',
            field=models.CharField(max_length=50),
        ),
    ]
