# Generated by Django 5.0.6 on 2024-08-15 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microapps', '0018_alter_run_ai_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='AiModelConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=50, unique=True)),
                ('frequency_penalty_min', models.FloatField(default=0)),
                ('frequency_penalty_max', models.FloatField(default=0)),
                ('presence_penalty_min', models.FloatField(default=0)),
                ('presence_penalty_max', models.FloatField(default=0)),
                ('top_p_min', models.FloatField(default=0)),
                ('top_p_max', models.FloatField(default=0)),
                ('temperature_min', models.FloatField(default=0)),
                ('temperature_max', models.FloatField(default=0)),
                ('max_tokens_default', models.IntegerField()),
                ('input_token_price', models.FloatField()),
                ('output_token_price', models.FloatField()),
            ],
        ),
    ]
