# Generated by Django 5.0.6 on 2024-09-12 05:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microapps', '0020_run_owner_id_alter_run_user_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='run',
            name='ma_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='microapps.microapp'),
        ),
        migrations.AlterField(
            model_name='run',
            name='owner_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='ma_owner_runs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='run',
            name='user_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_runs', to=settings.AUTH_USER_MODEL),
        ),
    ]
