# Generated by Django 5.0.6 on 2024-09-27 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microapps', '0025_alter_microapp_type_based_on_survey_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='microapp',
            name='ai_model',
            field=models.CharField(default='gpt-4o-mini', max_length=50),
            preserve_default=False,
        ),
    ]
