# Generated by Django 5.0.6 on 2024-10-02 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('microapps', '0026_microapp_ai_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='microapp',
            name='knowledge_base',
        ),
        migrations.RemoveField(
            model_name='microapp',
            name='max_output',
        ),
        migrations.RemoveField(
            model_name='microapp',
            name='max_prompts',
        ),
        migrations.RemoveField(
            model_name='microapp',
            name='shared_assets',
        ),
        migrations.RemoveField(
            model_name='run',
            name='credits',
        ),
    ]
