# Generated by Django 5.0.6 on 2024-10-02 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('microapps', '0027_remove_microapp_knowledge_base_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='run',
            old_name='skippable_phase',
            new_name='request_skip',
        ),
    ]
