# Generated by Django 5.0.6 on 2024-10-04 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microapps', '0028_rename_skippable_phase_run_request_skip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='run',
            name='minimum_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='run',
            name='no_submission',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='run',
            name='scored_run',
            field=models.BooleanField(default=False),
        ),
    ]
