# Generated by Django 5.0.6 on 2024-10-09 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microapps', '0032_update_app_json_with_page_titles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='microapp',
            name='type',
        ),
        migrations.AddField(
            model_name='microapp',
            name='privacy',
            field=models.CharField(default='Private', max_length=50),
        ),
        migrations.AlterField(
            model_name='microapp',
            name='ai_model',
            field=models.CharField(default='gpt-4o-mini', max_length=50),
        ),
        migrations.AlterField(
            model_name='microapp',
            name='copy_allowed',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='microapp',
            name='explanation',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='microapp',
            name='frequency_penalty',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='microapp',
            name='presence_penalty',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='microapp',
            name='temperature',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='microapp',
            name='title',
            field=models.CharField(default=('Untitled App',), max_length=50),
        ),
        migrations.AlterField(
            model_name='microapp',
            name='top_p',
            field=models.FloatField(default=1),
        ),
    ]
