# Generated by Django 5.0.6 on 2024-10-17 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microapps', '0034_alter_microapp_privacy_alter_microapp_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='microapp',
            name='privacy',
            field=models.CharField(choices=[('public', 'public'), ('private', 'private'), ('restricted', 'restricted')], default='private', max_length=50),
        ),
    ]
