# Generated by Django 5.0.6 on 2024-12-11 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microapps', '0040_unique_ids_to_app_json'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='run',
            name='prompt',
        ),
        migrations.AddField(
            model_name='run',
            name='app_hash_id',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='run',
            name='phase_instructions',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='run',
            name='price_scale',
            field=models.FloatField(default=1000000.0),
        ),
        migrations.AddField(
            model_name='run',
            name='response_type',
            field=models.CharField(choices=[('AI', 'AI'), ('Error', 'Error'), ('Fixed_Response', 'Fixed Response')], default='AI', max_length=20),
        ),
        migrations.AddField(
            model_name='run',
            name='system_prompt',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='run',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='run',
            name='user_prompt',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
    ]
