# Generated by Django 5.0.6 on 2025-01-17 23:53

from django.db import migrations, models

def calculate_credits(apps, schema_editor):
    Run = apps.get_model('microapps', 'Run')
    for run in Run.objects.all():
        # Calculate credits based on cost: credits = max(round(cost / 0.0001, 0), 1)
        run.credits = max(round(float(run.cost) / 0.0001, 0), 1)
        run.save()

def reverse_credits(apps, schema_editor):
    Run = apps.get_model('microapps', 'Run')
    for run in Run.objects.all():
        run.credits = 1
        run.save()

class Migration(migrations.Migration):

    dependencies = [
        ('microapps', '0043_microappuserjoin_is_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='credits',
            field=models.IntegerField(default=1),
        ),
        migrations.RunPython(calculate_credits, reverse_credits),
    ]
