# Generated by Django 5.0.6 on 2025-01-21 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microapps', '0044_run_credits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='run',
            name='credits',
            field=models.IntegerField(),
        ),
    ]
