# Generated by Django 5.0.6 on 2025-01-29 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('microapps', '0045_alter_run_credits'),
    ]

    operations = [
        migrations.DeleteModel(
            name='KnowledgeBase',
        ),
    ]
