# Generated by Django 5.0.6 on 2025-02-05 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microapps', '0046_delete_knowledgebase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='microapp',
            name='title',
            field=models.CharField(default='Untitled App', max_length=150),
        ),
    ]