# Generated by Django 5.1.6 on 2025-02-09 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microapps', '0047_alter_microapp_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aimodelconfig',
            name='max_tokens_default',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
