# Generated by Django 5.1.6 on 2025-02-09 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('microapps', '0049_rename_max_tokens_field'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aimodelconfig',
            old_name='max_tokens_default',
            new_name='max_tokens',
        ),
        migrations.RemoveField(
            model_name='run',
            name='price_input_token_1M',
        ),
        migrations.RemoveField(
            model_name='run',
            name='price_output_token_1M',
        ),
    ]
