# Generated by Django 5.1.6 on 2025-02-09 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('microapps', '0050_remove_token_price_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aimodelconfig',
            name='input_token_price',
        ),
        migrations.RemoveField(
            model_name='aimodelconfig',
            name='output_token_price',
        ),
        migrations.RemoveField(
            model_name='run',
            name='price_scale',
        ),
    ]
