# Generated by Django 5.0.6 on 2024-07-08 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalAssets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.TextField()),
                ('label', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='GlobalMicroapps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('explanation', models.TextField()),
                ('shared_assets', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=10)),
                ('knowledge_base', models.CharField(max_length=50)),
                ('max_output', models.IntegerField()),
                ('temperature', models.FloatField()),
                ('top_p', models.FloatField()),
                ('frequency_penalty', models.FloatField()),
                ('presence_penalty', models.FloatField()),
                ('max_prompts', models.IntegerField()),
                ('copy_allowed', models.BooleanField()),
                ('app_json', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='AssetsGaJoin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='global_microapps.globalassets')),
                ('global_app_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='global_microapps.globalmicroapps')),
            ],
        ),
    ]
