# Generated by Django 5.0.6 on 2024-07-15 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('global_microapps', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GlobalAssets',
            new_name='GlobalAsset',
        ),
    ]
