# Generated by Django 5.0.6 on 2024-10-02 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('global_microapps', '0002_rename_globalassets_globalasset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalmicroapps',
            name='copy_allowed',
            field=models.BooleanField(),
        ),
    ]
