# Generated by Django 5.0.6 on 2024-07-10 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microapps', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='run',
            name='assistant_id',
        ),
        migrations.RemoveField(
            model_name='run',
            name='thread_id',
        ),
        migrations.AddField(
            model_name='run',
            name='session_id',
            field=models.TextField(blank=True),
        ),
    ]
