# Generated by Django 5.0.6 on 2024-07-11 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microapps', '0002_remove_run_assistant_id_remove_run_thread_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='run',
            name='prompt',
            field=models.JSONField(),
        ),
    ]
