# Generated by Django 5.0.6 on 2024-07-15 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('microapps', '0008_rename_microapps_microapp'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Assets',
            new_name='Asset',
        ),
    ]
