# Generated by Django 5.0.6 on 2024-07-22 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microapps', '0011_alter_run_input_tokens_alter_run_max_tokens_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='run',
            name='ai_model',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='run',
            name='frequency_penalty',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='run',
            name='minimum_score',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='run',
            name='no_submission',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='run',
            name='presence_penalty',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='run',
            name='price_input_token_1M',
            field=models.DecimalField(decimal_places=6, max_digits=20),
        ),
        migrations.AlterField(
            model_name='run',
            name='price_output_token_1M',
            field=models.DecimalField(decimal_places=6, max_digits=20),
        ),
        migrations.AlterField(
            model_name='run',
            name='scored_run',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='run',
            name='temperature',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='run',
            name='top_p',
            field=models.FloatField(),
        ),
    ]
