# Generated by Django 5.0.6 on 2024-09-24 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microapps', '0023_alter_run_ma_id_alter_run_owner_id_alter_run_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='microapp',
            name='type',
            field=models.CharField(max_length=50),
        ),
    ]
