# Generated by Django 5.0.6 on 2024-10-07 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microapps', '0030_update_app_json_with_ai_prompts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='run',
            name='minimum_score',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='run',
            name='no_submission',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='run',
            name='scored_run',
            field=models.BooleanField(),
        ),
    ]
