# Generated by Django 5.0.6 on 2024-10-09 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microapps', '0033_remove_microapp_type_microapp_privacy_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='microapp',
            name='privacy',
            field=models.CharField(choices=[('public', 'public'), ('private', 'private'), ('restricted', 'restricted')], default='Private', max_length=50),
        ),
        migrations.AlterField(
            model_name='microapp',
            name='title',
            field=models.CharField(default='Untitled App', max_length=50),
        ),
    ]
