# Generated by Django 5.0.6 on 2024-10-18 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microapps', '0035_alter_microapp_privacy'),
    ]

    operations = [
        migrations.AddField(
            model_name='microapp',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
