# Generated by Django 5.0.6 on 2024-11-14 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microapps', '0036_microapp_is_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='microapp',
            name='hash_id',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
