# Generated by Django 5.0.6 on 2025-01-17 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microapps', '0041_remove_run_prompt_run_app_hash_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='microappuserjoin',
            name='counts_toward_max',
            field=models.BooleanField(default=False),
        ),
    ]
