# Generated by Django 5.0.6 on 2025-01-17 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microapps', '0042_microappuserjoin_counts_toward_max'),
    ]

    operations = [
        migrations.AddField(
            model_name='microappuserjoin',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
