# Generated by Django 5.1.6 on 2025-02-09 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('microapps', '0048_alter_aimodelconfig_max_tokens_default'),
    ]

    operations = [
    ]
