# Generated by Django 5.1.6 on 2025-02-18 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('microapps', '0051_eliminate_token_price_fields'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AiModelConfig',
        ),
    ]
