# Generated by Django 5.1.6 on 2025-06-06 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microapps', '0052_delete_aimodelconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='run_uuid',
            field=models.CharField(blank=True, max_length=36, null=True, unique=True),
        ),
    ]
