# Generated by Django 5.1.6 on 2025-01-27 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microapps', '0053_run_run_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='litellm_response_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
