# Generated by Django 5.2.5 on 2025-11-17 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microapps', '0056_remove_top_p'),
    ]

    operations = [
        migrations.AlterField(
            model_name='run',
            name='temperature',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
