# Generated by Django 5.2.5 on 2026-01-22 23:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microapps', '0057_make_temperature_nullable'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RubricBuild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('rubric_prompt', models.TextField(blank=True, default='')),
                ('files', models.JSONField(default=list)),
                ('rubric', models.TextField()),
                ('credits_spent', models.IntegerField()),
                ('model_used', models.CharField(max_length=50)),
                ('app_hash_id', models.CharField(blank=True, max_length=50)),
                ('user_ip', models.CharField(blank=True, max_length=20)),
                ('microapp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='microapps.microapp')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
