# Generated by Django 5.2.5 on 2026-07-14 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microapps', '0071_run_user_attachments'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='documentchunk',
            new_name='microapps_d_file_so_039d5d_idx',
            old_name='microapps_d_file_so_idx',
        ),
        migrations.AlterField(
            model_name='microapp',
            name='ai_model',
            field=models.CharField(default='claude-haiku-4-5-20251001', max_length=50),
        ),
    ]
