# Generated by Django 5.0.6 on 2024-10-17 08:00

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='body',
        ),
        migrations.AddField(
            model_name='homepage',
            name='content',
            field=wagtail.fields.StreamField([('heading', 0), ('paragraph', 1), ('bullet_list', 3)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Heading'}), 1: ('wagtail.blocks.RichTextBlock', (), {'label': 'Paragraph'}), 2: ('wagtail.blocks.CharBlock', (), {'label': 'Bullet'}), 3: ('wagtail.blocks.ListBlock', (2,), {})}),
        ),
    ]