# Generated by Django 5.0.6 on 2024-10-17 11:13

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_remove_homepage_body_homepage_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='content',
            field=wagtail.fields.StreamField([('heading', 0), ('paragraph', 1), ('bullet_list', 3)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Heading'}), 1: ('wagtail.blocks.RichTextBlock', (), {'features': ['h1', 'h2', 'h3', 'h4', 'h5', 'h6', 'bold', 'italic', 'link', 'ol', 'ul', 'hr', 'blockquote', 'code', 'superscript', 'subscript', 'strikethrough', 'image', 'embed'], 'label': 'Paragraph'}), 2: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'image'], 'label': 'Bullet'}), 3: ('wagtail.blocks.ListBlock', (2,), {})}),
        ),
    ]
