# Generated by Django 5.0.6 on 2024-11-13 21:29

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_alter_homepage_content'),
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.CreateModel(
            name='SampleAppsPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', models.TextField(blank=True, help_text='Introduction text to display at the top of the page')),
                ('apps', wagtail.fields.StreamField([('app', 4)], block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'App Screenshot'}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'App Title'}), 2: ('wagtail.blocks.TextBlock', (), {'label': 'App Description'}), 3: ('wagtail.blocks.URLBlock', (), {'label': 'App URL'}), 4: ('wagtail.blocks.StructBlock', [[('image', 0), ('title', 1), ('description', 2), ('url', 3)]], {})})),
            ],
            options={
                'verbose_name': 'Sample Apps Library',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='content',
            field=wagtail.fields.StreamField([('heading', 0), ('paragraph', 1), ('bullet_list', 3), ('image', 4), ('tile', 9), ('faq', 12)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Heading'}), 1: ('wagtail.blocks.RichTextBlock', (), {'features': ['h1', 'h2', 'h3', 'h4', 'h5', 'h6', 'bold', 'italic', 'link', 'ol', 'ul', 'hr', 'blockquote', 'code', 'superscript', 'subscript', 'strikethrough', 'image', 'embed'], 'label': 'Paragraph'}), 2: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'image'], 'label': 'Bullet'}), 3: ('wagtail.blocks.ListBlock', (2,), {}), 4: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Image'}), 5: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Tile Image'}), 6: ('wagtail.blocks.CharBlock', (), {'label': 'Tile Title'}), 7: ('wagtail.blocks.TextBlock', (), {'label': 'Tile Description'}), 8: ('wagtail.blocks.URLBlock', (), {'label': 'Target URL', 'required': False}), 9: ('wagtail.blocks.StructBlock', [[('image', 5), ('title', 6), ('description', 7), ('url', 8)]], {'label': 'Tile'}), 10: ('wagtail.blocks.CharBlock', (), {'label': 'Question'}), 11: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'ol', 'ul'], 'label': 'Answer'}), 12: ('wagtail.blocks.StructBlock', [[('question', 10), ('answer', 11)]], {'label': 'FAQ Item'})}),
        ),
    ]
