# Generated by Django 5.1.6 on 2025-02-18 13:52

import django.db.models.deletion
from django.db import migrations, models


def forward_func(apps, schema_editor):
    # Set any invalid customer_id references to NULL
    Team = apps.get_model('teams', 'Team')
    StripeCustomer = apps.get_model('subscriptions', 'StripeCustomer')
    
    # Get all valid customer IDs
    valid_customer_ids = StripeCustomer.objects.values_list('id', flat=True)
    
    # Update teams with invalid customer references to NULL
    Team.objects.exclude(customer_id__in=valid_customer_ids).update(customer=None)
    Team.objects.exclude(subscription_id__in=valid_customer_ids).update(subscription=None)


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0008_alter_billingcycle_team_stripecustomer_subscription_and_more'),
        ('teams', '0003_team_billing_details_last_changed_team_customer_and_more'),
    ]

    operations = [
        migrations.RunPython(forward_func, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='team',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='subscriptions.stripecustomer'),
        ),
        migrations.AlterField(
            model_name='team',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='subscriptions.subscription'),
        ),
    ]
