# Generated by Django 5.0.6 on 2024-07-02 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MicroAppTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(help_text='micro app name', max_length=50, unique=True)),
                ('app_json', models.JSONField(help_text='json for app')),
            ],
        ),
    ]
