# Generated by Django 5.0.6 on 2024-07-03 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microapp_templates', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='microapptemplate',
            name='app_json',
            field=models.JSONField(help_text='micro-app json'),
        ),
        migrations.AlterField(
            model_name='microapptemplate',
            name='app_name',
            field=models.CharField(help_text='micro-app name', max_length=50, unique=True),
        ),
    ]
