name: CI/CD Backend Production

on:
  push:
    branches:
      - master_change_me

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  prepare:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Build Web
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: 'ubuntu'
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd /home/ubuntu/micro_ai
            git pull origin master
            
            # ensure db and redis are up
            docker-compose -p backend -f docker-compose.prod.yml up -d redis
            docker-compose -p backend -f docker-compose.prod.yml up -d db            

  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    needs: prepare

    steps:
      - name: Build Web
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: 'ubuntu'
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd /home/ubuntu/micro_ai
            git pull origin master
            docker-compose -p backend -f docker-compose.prod.yml build web-staging

      - name: Build Celery
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: 'ubuntu'
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd /home/ubuntu/micro_ai
            git pull origin master
            docker-compose -p backend -f docker-compose.prod.yml build celery 

  staging:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    needs: build

    steps:
      - name: Deploy Staging
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: 'ubuntu'
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            if [ -d "/docker/volumes/backend-staging" ]; then
              cd /docker/volumes/backend-staging
              docker-compose -p backend -f docker-compose.prod.yml down web-staging
              docker-compose -p backend -f docker-compose.prod.yml down celery
            else
              echo "Directory /docker/volumes/backend-staging does not exist. Skipping."
            fi
            
            cd /home/ubuntu/micro_ai
            rsync -r --delete ./ /docker/volumes/backend-staging
            
            cd /docker/volumes/backend-staging
            docker-compose -p backend -f docker-compose.prod.yml up -d web-staging
            docker-compose -p backend -f docker-compose.prod.yml up -d celery

  clean:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    needs: staging

    steps:
      - name: Deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: 'ubuntu'
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            
            echo "Pruning unused Docker resources..."
            # Only remove stopped containers
            sudo docker container prune -f
            # Only remove dangling images
            sudo docker image prune -f
            # Never prune volumes automatically
            sudo docker builder prune -f
            
            # Optional: List unused volumes (but don't remove them automatically)
            echo "Listing unused volumes (for information only):"
            for volume in $(sudo docker volume ls -q); do
               if ! sudo docker ps -a --filter volume=$volume | grep -q .; then
                  echo "Unused volume found: $volume"
               fi
            done