name: CI/CD Backend

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3  

    - name: Install Docker
      run: |
        curl -fsSL https://get.docker.com -o get-docker.sh
        sh get-docker.sh

    - name: Run Tests
      run: |
        docker-compose up -d
        docker-compose run --rm --no-deps web python manage.py test

    - name: SSH Command for Deployment
      uses: appleboy/ssh-action@v0.1.0
      with:
        host: ${{ secrets.SERVER_IP }}
        username: 'root'
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        script: |
          cd /home/ubuntu/micro_ai
          git pull origin feature/proxy-server
          docker-compose down
          sudo docker-compose -f docker-compose-prod.yml up -d