name: CI/CD Backend

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4 

    - name: Check Docker Version
      run: |
        docker --version
        docker compose version

    - name: Copy .env.example to .env
      run: |
        cp .env.example .env

    # TODO: breaks with an error
    # - name: Run Tests
    #   run: |
    #     docker compose up -d
    #     docker compose run --rm --no-deps web python manage.py test

    - name: SSH Command for Deployment
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SERVER_IP }}
        username: 'ubuntu'
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        script: |
          cd /home/ubuntu/microai-frontend
          sudo docker-compose -f docker-compose.prod.yml down
          cd /home/ubuntu/micro_ai
          sudo docker-compose -f docker-compose-prod.yml down
          git pull origin master
          sudo docker-compose -f docker-compose-prod.yml build --no-cache
          sudo docker-compose -f docker-compose-prod.yml up -d
          cd /home/ubuntu/microai-frontend
          sudo docker-compose -f docker-compose.prod.yml up -d          