name: CI/CD Frontend (Dev)
# This workflow is triggered by a push to the dev branch, and builds the frontend and deploys it to the dev server.

on:
  push:
    branches:
      - dev

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      #Takes the .env.template file and copies it to .env. You should use another process (e.g. Github Secrets) to set the real variables in .env.
      - name: Copy .env.template to .env
        run: |
          cp .env.template .env

      #Builds the docker image and runs lint
      - name: Build Docker Image
        run: |
          docker run --rm \
              -v $(pwd):/app \
              -w /app \
              --user $(id -u):$(id -g) \
              node:20-alpine \
              sh -c "yarn install && yarn lint"

  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    needs: lint

    steps:
      - name: pull dev branch
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_IP_DEV }}
          username: 'ubuntu'
          key: ${{ secrets.SSH_PRIVATE_KEY_DEV }}
          port: 22
          script: |
            cd /home/ubuntu/microai-frontend
            git pull origin dev

      - name: build frontend containers
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_IP_DEV }}
          username: 'ubuntu'
          key: ${{ secrets.SSH_PRIVATE_KEY_DEV }}
          port: 22
          script: |
            cd /home/ubuntu/microai-frontend
            docker-compose -p frontend -f docker-compose.dev.yml build frontend

  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    needs: build

    steps:
    # StopAndRemove (down) the old front-end containers, sync the code, and start the new front-end containers
      - name: start frontend containers
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_IP_DEV }}
          username: 'ubuntu'
          key: ${{ secrets.SSH_PRIVATE_KEY_DEV }}
          port: 22
          script: |
            if [ -d "/docker/volumes/frontend" ]; then
               cd /docker/volumes/frontend
               docker-compose -p frontend -f docker-compose.prod.yml down frontend
            else
              echo "Directory /docker/volumes/frontend does not exist. Skipping."
            fi
          
            
            cd /home/ubuntu/microai-frontend
            rsync -r --delete ./ /docker/volumes/frontend

            cd /docker/volumes/frontend
            docker-compose -p frontend -f docker-compose.dev.yml up --force-recreate -d frontend

  cleanup:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    needs: deploy

    steps:
      - name: prune unused docker resources
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_IP_DEV }}
          username: 'ubuntu'
          key: ${{ secrets.SSH_PRIVATE_KEY_DEV }}
          port: 22
          script: |
            echo "Pruning unused Docker resources..."
            # Only remove stopped containers
            sudo docker container prune -f
            # Only remove dangling images
            sudo docker image prune -f
            # Never prune volumes automatically
            sudo docker builder prune -f

            # Optional: List unused volumes (but don't remove them automatically)
            echo "Listing unused volumes (for information only):"
            for volume in $(sudo docker volume ls -q); do
               if ! sudo docker ps -a --filter volume=$volume | grep -q .; then
                  echo "Unused volume found: $volume"
               fi
            done