name: Postgresql+Redis Production

on:
  workflow_dispatch:
    inputs:
      force_recreate:
        description: 'Force Recreate?'
        required: false
        default: 'false'
        type: boolean
      containers:
        description: 'Containers to Up/Recreate'
        required: true
        default: 'both'
        type: choice
        options:
          - db
          - redis
          - both

jobs:
  recreate_nginx:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Build Web
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: 'ubuntu'
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd /docker/ubuntu/micro_ai
            git pull origin main
            
            # ensure db and redis are up
            FORCE_RECREATE=""
            if [ "${{ inputs.force_recreate }}" = "true" ]; then
             FORCE_RECREATE="--force-recreate"
            fi
            
            CONTAINERS=""
            if [ "${{ inputs.containers }}" = "both" ]; then
              CONTAINERS="redis db"
            else
              CONTAINERS="${{ inputs.containers }}"
            fi
            
            docker-compose -p backend -f docker-compose-dev.yml up -d $FORCE_RECREATE $CONTAINERS